#ifndef __LANGUAGE_EN_H__
#define __LANGUAGE_EN_H__

// BEHAVIOR
#define _T0001 "You open the chest with the key"
#define _T0002 "Just because I can't see you doesn't\r\nmean I can't sense your presence"
#define _T0003 "Hey! Do you think I can't see you?"
#define _T0004 "You listen to your inner voice"
#define _T0005 "Better keep it"
#define _T0006 "You play a few random notes"
#define _T0007 "You blow into the scepter.\r\nIt makes a hollow sound"
#define _T0008 "POC!"
#define _T0009 "DING"
#define _T0010 "BONG"
#define _T0011 "SLURP"
#define _T0012 "The cauldron contains a %s liquid"
#define _T0013 "The statue turns,the door slides"
#define _T0014 "It doesn't move"
#define _T0015 "You attach the whistle to the end\r\nof the scepter."
#define _T0016 "You play the sheet music"
#define _T0017 "You can SEARCH it"
#define _T0018 "You lock the chest"
#define _T0019 "It's stuck with rust"
#define _T0020 "A golden whistle is attached\r\nto his flute"
#define _T0021 "A sheet of music rests on the stand"
#define _T0022 "A staircase leads down to the basement"
#define _T0023 "The hatch is closed"
#define _T0024 "It's already lit"
#define _T0025 "It's already off"
#define _T0026 "You light the stove"
#define _T0027 "You turn off the stove"
#define _T0028 "You stir the mixture with the TIBIA"
#define _T0029 "The vial is empty"
#define _T0030 "A %s liquid"
#define _T0031 "The VIAL is empty"
#define _T0032 "You empty the VIAL"
#define _T0033 "The VIAL is already full"
#define _T0034 "It's locked"
#define _T0035 "The lock is stuck"
#define _T0036 "You lock the chest"
#define _T0037 "The lock is stuck"
#define _T0038 "You unlock %s"
#define _T0039 "The POKER fits perfectly into the hole"
#define _T0040 "The POKER is already in place"
#define _T0041 "The mirror is firmly fixed to the wall"
#define _T0042 "You try to pass through the mirror"
#define _T0043 "but the more you push, the more it\r\nresists"
#define _T0044 "No way I'm giving up now!"
#define _T0045 "Only the fall of a few debris from\r\nthe roof answers you"
#define _T0046 "The door is closed"
#define _T0047 "TIBIA"
#define _T0048 "You're not going to mix it by hand!"
#define _T0049 "SALT"
#define _T0050 "PEPPER"
#define _T0051 "Impossible to go down, the ladder\r\nis broken halfway"
#define _T0052 "You shall not pass!"
#define _T0053 "You knock out the guard"
#define _T0054 "You need a strong argument to defeat me"
#define _T0055 "You unlock %s"
#define _T0056 "Remember to specify WHERE to use the key"

// GAME
#define _T0057 "SICK"
#define _T0058 "SHINY"
#define _T0059 "INVISIBLE"
#define _T0060 "NERVOUS"
#define _T0061 "TIRED"
#define _T0062 "%s It's settled: Blow everything up"
#define _T0063 "%s Finally Free: Kill the Creator"
#define _T0064 "%s Soulless Seed: Kill Nahash"
#define _T0065 "%s Balance: Restore harmony"
#define _T0066 "%s Messiah: Win on turn 1"
#define _T0067 "You already have %s in your inventory"
#define _T0068 "You take %s"
#define _T0069 "I don't know what to take"
#define _T0070 "You can't take %s"
#define _T0071 "You open %s"
#define _T0072 "%s is already open"
#define _T0073 "%s is locked"
#define _T0074 "You close %s"
#define _T0075 "%s is already closed"
#define _T0076 "You put %s into %s"
#define _T0077 "It doesn't fit"
#define _T0078 "%s is closed"

// PARSER
#define _T0079 "Sorry, I didn't understand"
#define _T0080 "You can't go north"
#define _T0081 "You can't go south"
#define _T0082 "You can't go east"
#define _T0083 "You can't go west"
#define _T0084 "No way up"
#define _T0085 "You don't fall for it"
#define _T0086 "Nothing to see"
#define _T0087 "Nothing interesting"
#define _T0088 "You can't take that"
#define _T0089 "It doesn't work"
#define _T0090 "Not just anywhere"
#define _T0091 "It's ineffective"
#define _T0092 "No need to push!"
#define _T0093 "You're going full circle!"
#define _T0094 "You check your inventory"
#define _T0095 "No time to dawdle"
#define _T0096 "It's bad for your figure"
#define _T0097 "You shall not pass"
#define _T0098 "You're not fit to go out!"
#define _T0099 "It doesn't open"
#define _T0100 "It doesn't close"
#define _T0101 "It goes without reading!"
#define _T0102 "No answer"
#define _T0103 "No one will hear you scream"
#define _T0104 "No time to waste"
#define _T0105 "Avoid mixing everything up"
#define _T0106 "Nothing is played yet"
#define _T0107 "Are you sour?"
#define _T0108 "Achoo!"
#define _T0109 "It's worse to fill up"
#define _T0110 "It can't be drained"
#define _T0111 "Save failed" // Sauver
#define _T0112 "Load failed" // Charger

// ALCHEMY
#define _T0113 "black"
#define _T0114 "dark"
#define _T0115 "blue"
#define _T0116 "purple"
#define _T0117 "red"
#define _T0118 "golden"
#define _T0119 "orange"
#define _T0120 "pink"
#define _T0121 "green"
#define _T0122 "colorless"
#define _T0123 "yellow"
#define _T0124 "white"
#define _T0125 "It's added to the cauldron"
#define _T0126 "You fill the FLASK"
#define _T0127 "The flask is empty"
#define _T0128 "You drink the contents of the flask"

// BOOK
#define _T0129 "Back"
#define _T0130 "Light"
#define _T0131 "Invisibility"
#define _T0132 "Stimulant"
#define _T0133 "Sedative"
#define _T0134 "Dawn"
#define _T0135 "Close"

// recipeShiny
#define _T0136 "-When the substrate is yellow,add salt"
#define _T0137 "-Stir when it turns orange"
#define _T0138 "-At pink,add the berries"
#define _T0139 "Remember to shut down the heat otherwise"
#define _T0140 "the substrate will regain its initial"
#define _T0141 "properties as soon as it turns white."

// recipeInvisible
#define _T0142 "-At yellow,add the berries"
#define _T0143 "-Stir at orange"
#define _T0144 "-At pink,add the pepper"
#define _T0145 "This recipe is the TRANSPOSED version\r\nof the light potion"

// recipeNervous
#define _T0146 "-Light the fire and add salt"
#define _T0147 "-Immediately add the mint"
#define _T0148 "-Stop heating"
#define _T0149 "-At yellow,stir."
#define _T0150 "If everything went well,\r\nthe liquid should turn green."

// recipeSleepy
#define _T0151 "-TRANSPOSE the recipe of the stimulant"
#define _T0152 "potion"
#define _T0153 "WARNING: this mixture is\r\nindistinguishable from its TRANSPOSITION"

// recipeBeginning
#define _T0154 "-Light the fire and add salt"
#define _T0155 "-After one hourglass,add mushroom"
#define _T0156 "-Bring it to orange and stir"
#define _T0157 "WARNING:NEVER TRANSPOSE THIS RECIPE"

// DIALOG
// finEpreuve
#define _T0158 "Go,find Orpheus' Scepter"
#define _T0159 "It is the key to the curse that\r\nhas befallen your people"

// dialogHermit
#define _T0160 "Mmmh?Uh… Yes… What is it?"
#define _T0161 "How can I help you?"
#define _T0162 "It's been a long time since\r\nI had any visitors."
#define _T0163 "My name is Hermes,I am a monk\r\nand an alchemist in my spare time."
#define _T0164 "What is this amulet again?"
#define _T0165 "How do I get out of here?"
#define _T0166 "I am looking for Orpheus' Scepter"
#define _T0167 "I need this key!"
#define _T0168 "Offer a drink"
#define _T0169 "Bye"
#define _T0170 "Here is an amulet that allows you to\r\ncross the mirror"
#define _T0171 "You can keep it"
#define _T0172 "It is for crossing the mirror"
#define _T0173 "The amulet prevents it from seeing you"
#define _T0174 "Don't touch this artifact,\r\nit is dangerous"
#define _T0175 "Anyway,I locked it up"
#define _T0176 "No way,the scepter is too dangerous!"
#define _T0177 "Mint tea,my favorite drink.\r\nThank you very much!"
#define _T0178 "I feel a little tired.\r\nI think I will take a nap."
#define _T0179 "Ah!Thank you,I feel refreshed!"
#define _T0180 "I would love some mint tea"
#define _T0181 "Here are some mint leaves to prepare it"
#define _T0182 "Goodbye"

// dialogDieu
#define _T0183 "My creation has been corrupted by Nahash"
#define _T0184 "I created the world with"
#define _T0185 "unchangeable rules"
#define _T0186 "There is no place for free"
#define _T0187 "will"
#define _T0188 "Destroy the part of Nahash within you"
#define _T0189 "to restore this world to its original"
#define _T0190 "beauty."

// endingMessage
#define _T0191 "Nahash:You helped me destroy\r\nyour world."
#define _T0192 "I will use the energy of this\r\ndestruction to create a universe in my\r\nimage."
#define _T0193 "To thank you,here is your kingdom!\r\nYou are free to stay here for eternity…"

#define _T0194 "You wake up in the church.\r\nYou struggle to remember why\r\nyou came here."
#define _T0195 "Back home,the village is deserted,\r\nand you feel your mind slowly slipping\r\naway."

#define _T0196 "You wake up in the church.As you\r\nreturn to your village,you are carried\r\nby the feeling of a\r\nfulfilled duty."

#define _T0197 "The explosion was so strong that\r\nit destroyed half the country.\r\nThere is not much left to save now.\r\nBut in any case,you are no longer\r\nable to do so."

// ending
#define _T0198 "List of endings achieved"
#define _T0199 "Return to the last checkpoint"

// SCENE
// introNahash
#define _T0200 "Rubble falls from the walls and some\r\nstones drop from the ceiling"
#define _T0201 "I am the God Nahash,and I have\r\nheard your prayer"
#define _T0202 "This world is a trial"
#define _T0203 "Master its rules and find the way out"

// gameState
#define _T0204 "Game saved"
#define _T0205 "No save found"
#define _T0206 "Game loaded"

// introMenu
#define _T0207 "North"
#define _T0208 "South"
#define _T0209 "Call"

#endif
